micronaut:
  application:
    name: micronautJwt
  security:
    authentication: bearer
    token:
      jwt:
        generator:
          refresh-token:
            secret: ${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}
            enabled: true
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}
netty:
  default:
    allocator:
      max-order: 3
